GET http://localhost:3001/api/users HTTP/1.1
content-type: application/json

POST http://localhost:3001/api/users HTTP/1.1
content-type: application/json

{  
    "username": "TESTusername99",
    "password": "TESTpassword99"
}

POST http://localhost:3001/api/login HTTP/1.1
content-type: application/json

{  
    "username": "TESTusername99",
    "password": "TESTpassword99"
}

POST http://localhost:3001/api/blogs HTTP/1.1
content-type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlRFU1R1c2VybmFtZTk5IiwiaWQiOiI2MzVhYTM3ZjEwZmFjYzlkN2I0ODQ5ZDIiLCJpYXQiOjE2NjY4ODQ0OTgsImV4cCI6MTY2Njg4ODA5OH0.0QmZ3CZ9HrQiWN8IR8znR18u1TUD94ABM3tKcIUmUH8

{  
    "title": "TESTtitleWithTOKEN123",
    "author": "TESTauthorWithTOKEN123",
    "url": "TESTurlWithTOKEN123"
}

DELETE http://localhost:3001/api/blogs/635aa3aa10facc9d7b4849d6
content-type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlRFU1R1c2VybmFtZTk5IiwiaWQiOiI2MzVhYTM3ZjEwZmFjYzlkN2I0ODQ5ZDIiLCJpYXQiOjE2NjY4ODQ0OTgsImV4cCI6MTY2Njg4ODA5OH0.0QmZ3CZ9HrQiWN8IR8znR18u1TUD94ABM3tKcIUmUH8