GET http://localhost:3001/api/users HTTP/1.1
content-type: application/json

POST http://localhost:3001/api/users HTTP/1.1
content-type: application/json

{  
    "username": "TESTusername5",
    "password": "TESTpassword5"
}

POST http://localhost:3001/api/login HTTP/1.1
content-type: application/json

{  
    "username": "TESTusername",
    "password": "TESTpassword"
}

POST http://localhost:3001/api/blogs HTTP/1.1
content-type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlRFU1R1c2VybmFtZSIsImlkIjoiNjM1N2QzYWJkZjgwMDAyNTQ4ZTg5YTMyIiwiaWF0IjoxNjY2ODc0OTYxLCJleHAiOjE2NjY4Nzg1NjF9.gDEeW0AhXoz-r9d-O4Yq8ooWGjvBt2-kgqhj8lptLlQ

{  
    "title": "TESTtitleWithTOKEN30",
    "author": "TESTauthorWithTOKEN30",
    "url": "TESTurlWithTOKEN30"
}

DELETE http://localhost:3001/api/blogs/63593cea5f61967032de1df1
content-type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlRFU1R1c2VybmFtZSIsImlkIjoiNjM1N2QzYWJkZjgwMDAyNTQ4ZTg5YTMyIiwiaWF0IjoxNjY2ODc0OTYxLCJleHAiOjE2NjY4Nzg1NjF9.gDEeW0AhXoz-r9d-O4Yq8ooWGjvBt2-kgqhj8lptLlQ