GET http://localhost:3001/api/users HTTP/1.1
content-type: application/json

POST http://localhost:3001/api/users HTTP/1.1
content-type: application/json

{  
    "username": "TESTusername5",
    "password": "TESTpassword5"
}

POST http://localhost:3001/api/login HTTP/1.1
content-type: application/json

{  
    "username": "TESTusername",
    "password": "TESTpassword"
}

POST http://localhost:3001/api/blogs
content-type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlRFU1R1c2VybmFtZSIsImlkIjoiNjM1N2QzYWJkZjgwMDAyNTQ4ZTg5YTMyIiwiaWF0IjoxNjY2NzkyMDk0fQ.WYME2ABXFjpJv4jHBBkkv6R_tiTWCgsCZnVMGf2mUHk

{  
    "title": "TESTtitleWithTOKEN",
    "author": "TESTauthorWithTOKEN",
    "url": "TESTurlWithTOKEN",
    "likes": 555555
}